spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.102.205.163:8848
    gateway:
      routes:
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: baidu_route
          uri: https://www.jd.com
          predicates:
            - Query=url,baidu
  application:
    name: shop-gateway
server:
  port: 8095